const personagens = [ { nome: "Peter Parker", codinome: "Homem-Aranha", armaPrincipal: "Lançadores de teia", armaSecundaria: "Sentido aranha", velocidade: 90, forca: 65, resistencia: 75 }, 
                          { nome: "Stephen Strange", codinome: "Doutor Estranho", armaPrincipal: "Magia das Artes Místicas", armaSecundaria: "Olho de Agamotto", velocidade: 70, forca: 60, resistencia: 80 }, 
                                                { nome: "T'Challa", codinome: "Pantera Negra", armaPrincipal: "Traje de Vibranium", armaSecundaria: "Garras retráteis", velocidade: 85, forca: 80, resistencia: 85 }, 
                                                                      { nome: "Wanda Maximoff", codinome: "Feiticeira Escarlate", armaPrincipal: "Magia do Caos", armaSecundaria: "Telecinese", velocidade: 75, forca: 90, resistencia: 80 }, 
                                                                                            { nome: "Wade Wilson", codinome: "Deadpool", armaPrincipal: "Katanas", armaSecundaria: "Fator de cura", velocidade: 80, forca: 75, resistencia: 95 }, 
                                                                                                                  { nome: "Thanos", codinome: "Thanos", armaPrincipal: "Manopla do Infinito", armaSecundaria: "Super força", velocidade: 65, forca: 100, resistencia: 100 } ];

                                                                                                                  function compararPersonagens() { for (let i = 0; i < personagens.length; i++) { for (let j = i + 1; j < personagens.length; j++) { const p1 = personagens[i]; const p2 = personagens[j];

                                                                                                                  console.log(`\nComparação entre ${p1.codinome} e ${p2.codinome}:`);
                                                                                                                          console.log(`${p1.codinome}: Força = ${p1.forca}, Velocidade = ${p1.velocidade}, Resistência = ${p1.resistencia}`);
                                                                                                                                  console.log(`${p2.codinome}: Força = ${p2.forca}, Velocidade = ${p2.velocidade}, Resistência = ${p2.resistencia}`);

                                                                                                                                          if (p1.forca > p2.forca) {
                                                                                                                                                      console.log(`${p1.codinome} vence em Força contra ${p2.codinome}.`);
                                                                                                                                                              } else if (p1.forca < p2.forca) {
                                                                                                                                                                          console.log(`${p2.codinome} vence em Força contra ${p1.codinome}.`);
                                                                                                                                                                                  } else {
                                                                                                                                                                                              console.log(`${p1.codinome} e ${p2.codinome} têm a mesma Força.`);
                                                                                                                                                                                                      }

                                                                                                                                                                                                              if (p1.velocidade > p2.velocidade) {
                                                                                                                                                                                                                          console.log(`${p1.codinome} vence em Velocidade contra ${p2.codinome}.`);
                                                                                                                                                                                                                                  } else if (p1.velocidade < p2.velocidade) {
                                                                                                                                                                                                                                              console.log(`${p2.codinome} vence em Velocidade contra ${p1.codinome}.`);
                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                  console.log(`${p1.codinome} e ${p2.codinome} têm a mesma Velocidade.`);
                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                  if (p1.resistencia > p2.resistencia) {
                                                                                                                                                                                                                                                                                              console.log(`${p1.codinome} vence em Resistência contra ${p2.codinome}.`);
                                                                                                                                                                                                                                                                                                      } else if (p1.resistencia < p2.resistencia) {
                                                                                                                                                                                                                                                                                                                  console.log(`${p2.codinome} vence em Resistência contra ${p1.codinome}.`);
                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                      console.log(`${p1.codinome} e ${p2.codinome} têm a mesma Resistência.`);
                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                      console.log("---------------------------------");
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                          compararPersonagens();
]